name: dotnet-build
on: 
  workflow_dispatch:
  push:
      branches:
        - main
env:
    DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4        
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore
      - name: build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
      - name: Publish
        run: dotnet publish -c Release -o ./publish
      - name: Uplpoad artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish
