name: dotnet-build
on: 
  push:
   branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4        
      - name: Setip .NET
        uses: actions/checkout@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
      - name: Publish
        run: dotnet publish -c Release -o ./publish
      - name: Uplpoad artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish
