name: To do list rest services
on: 
  workflow_dispatch:
  push:
      branches:
        - master
env:
    AZURE_WEBAPP_NAME: 'restapiTodolist'
    AZURE_WEBAPP_PACKAGE_PATH: './publish'
    DOTNET_VERSION: '8.0.x'
    SOLUTION_PATH: 'Dev4Side.sln'
    API_PROJECT_PATH: 'WebAPITodoList'
    PUBLISH_DIR: './publish'
jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo code
              uses: actions/checkout@v4
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
            - name: Restore dependencies
              run: dotnet restore ${{ env.SOLUTION_PATH }}
            - name: Build the project
              run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release
            - name: Run tests
              run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --configuration Release --no-restore --verbosity normal
            - name: Publish the project
              run: dotnet publish ${{ env.API_PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }} --no-build --no-restore
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: webapp
                path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    deploy:
        name: Deploy to Azure Web App
        runs-on: ubuntu-latest
        needs: [build-and-test]

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: webapp
                path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}